import {
  ANNOUNCEMENT_EVENT_KEYS,
  ANNOUNCEMENT_TYPES,
} from "./announcementTypes.js";

export const RECENT_ACTIVITY_ACTION_BY_EVENT_KEY = Object.freeze({
  [ANNOUNCEMENT_EVENT_KEYS.INQUIRY_ALLOCATED]: "Updated inquiry allocation",
  [ANNOUNCEMENT_EVENT_KEYS.QUOTE_CREATED]: "Created quote/job",
  [ANNOUNCEMENT_EVENT_KEYS.QUOTE_SENT]: "Updated quote",
  [ANNOUNCEMENT_EVENT_KEYS.QUOTE_ACCEPTED]: "Updated quote",
  [ANNOUNCEMENT_EVENT_KEYS.INVOICE_TRIGGERED]: "Updated invoice",
  [ANNOUNCEMENT_EVENT_KEYS.BILL_APPROVED]: "Updated bill",
  [ANNOUNCEMENT_EVENT_KEYS.INVOICE_SENT_TO_CUSTOMER]: "Updated invoice",
  [ANNOUNCEMENT_EVENT_KEYS.PAYMENT_STATUS_CHANGED]: "Updated payment status",
  [ANNOUNCEMENT_EVENT_KEYS.POST_CREATED]: "Created memo post",
  [ANNOUNCEMENT_EVENT_KEYS.COMMENT_CREATED]: "Created memo comment",
  [ANNOUNCEMENT_EVENT_KEYS.ACTIVITY_ADDED]: "Created activity",
  [ANNOUNCEMENT_EVENT_KEYS.MATERIAL_ADDED]: "Created material",
  [ANNOUNCEMENT_EVENT_KEYS.APPOINTMENT_SCHEDULED]: "Created appointment",
  [ANNOUNCEMENT_EVENT_KEYS.APPOINTMENT_COMPLETED]: "Updated appointment",
  [ANNOUNCEMENT_EVENT_KEYS.TASK_ADDED]: "Created task",
  [ANNOUNCEMENT_EVENT_KEYS.TASK_COMPLETED]: "Updated task",
  [ANNOUNCEMENT_EVENT_KEYS.UPLOAD_ADDED]: "Created upload",
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_CREATED]: "Created property",
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_UPDATED]: "Updated property",
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_LINKED]: "Updated property link",
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_AFFILIATION_ADDED]: "Created property affiliation",
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_AFFILIATION_UPDATED]: "Updated property affiliation",
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_AFFILIATION_DELETED]: "Deleted property affiliation",
});

export const EVENT_CONFIG = {
  [ANNOUNCEMENT_EVENT_KEYS.INQUIRY_ALLOCATED]: {
    type: ANNOUNCEMENT_TYPES.INQUIRY,
    tab: "Overview",
    focusKind: "inquiry",
    title: "New inquiry allocation",
    content: "A new inquiry has been allocated to you.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.QUOTE_CREATED]: {
    type: ANNOUNCEMENT_TYPES.QUOTE_JOB,
    tab: "Overview",
    focusKind: "quote",
    title: "Quote created",
    content: "A new quote has been created and linked.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.QUOTE_SENT]: {
    type: ANNOUNCEMENT_TYPES.QUOTE_JOB,
    tab: "Overview",
    focusKind: "quote_sent",
    title: "Quote sent",
    content: "A quote was sent to the customer.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.QUOTE_ACCEPTED]: {
    type: ANNOUNCEMENT_TYPES.QUOTE_JOB,
    tab: "Overview",
    focusKind: "quote_accepted",
    title: "Quote accepted",
    content: "A quote has been accepted.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.INVOICE_TRIGGERED]: {
    type: ANNOUNCEMENT_TYPES.QUOTE_JOB,
    tab: "Invoice & Payment",
    focusKind: "invoice",
    title: "Invoice updated",
    content: "Invoice generation/update was requested.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.BILL_APPROVED]: {
    type: ANNOUNCEMENT_TYPES.QUOTE_JOB,
    tab: "Invoice & Payment",
    focusKind: "bill",
    title: "Bill approved",
    content: "Bill was approved by admin.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.INVOICE_SENT_TO_CUSTOMER]: {
    type: ANNOUNCEMENT_TYPES.QUOTE_JOB,
    tab: "Invoice & Payment",
    focusKind: "invoice_send",
    title: "Invoice sent",
    content: "Invoice was queued for customer delivery.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.PAYMENT_STATUS_CHANGED]: {
    type: ANNOUNCEMENT_TYPES.QUOTE_JOB,
    tab: "Invoice & Payment",
    focusKind: "payment",
    title: "Payment status changed",
    content: "Payment status was updated.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.POST_CREATED]: {
    type: ANNOUNCEMENT_TYPES.POST,
    tab: "Overview",
    focusKind: "post",
    openMemo: true,
    title: "New memo post",
    content: "A new memo post was added.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.COMMENT_CREATED]: {
    type: ANNOUNCEMENT_TYPES.COMMENT,
    tab: "Overview",
    focusKind: "comment",
    openMemo: true,
    title: "New memo comment",
    content: "A new memo reply was added.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.ACTIVITY_ADDED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Activities",
    focusKind: "activity",
    title: "New activity",
    content: "A new activity was added.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.MATERIAL_ADDED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Materials",
    focusKind: "material",
    title: "New material",
    content: "A new material item was added.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.APPOINTMENT_SCHEDULED]: {
    type: ANNOUNCEMENT_TYPES.APPOINTMENT,
    tab: "Appointments",
    focusKind: "appointment",
    title: "Appointment scheduled",
    content: "A new appointment was scheduled.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.APPOINTMENT_COMPLETED]: {
    type: ANNOUNCEMENT_TYPES.APPOINTMENT,
    tab: "Appointments",
    focusKind: "appointment",
    title: "Appointment completed",
    content: "An appointment was marked as completed.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.TASK_ADDED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Tasks",
    focusKind: "task",
    title: "New task",
    content: "A new task was added.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.TASK_COMPLETED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Tasks",
    focusKind: "task",
    title: "Task completed",
    content: "A task was marked as completed.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.UPLOAD_ADDED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Uploads",
    focusKind: "upload",
    title: "New upload",
    content: "A new file was uploaded.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_CREATED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Overview",
    focusKind: "property",
    title: "Property created",
    content: "A new property was created.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_UPDATED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Overview",
    focusKind: "property",
    title: "Property updated",
    content: "Property details were updated.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_LINKED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Overview",
    focusKind: "property_link",
    title: "Property linked",
    content: "A property was linked to this record.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_AFFILIATION_ADDED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Overview",
    focusKind: "affiliation",
    title: "Property contact added",
    content: "A property contact link was added.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_AFFILIATION_UPDATED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Overview",
    focusKind: "affiliation",
    title: "Property contact updated",
    content: "A property contact link was updated.",
  },
  [ANNOUNCEMENT_EVENT_KEYS.PROPERTY_AFFILIATION_DELETED]: {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Overview",
    focusKind: "affiliation",
    title: "Property contact removed",
    content: "A property contact link was removed.",
  },
};

export function getEventConfig(eventKey) {
  return EVENT_CONFIG[eventKey] || {
    type: ANNOUNCEMENT_TYPES.ACTIVITY,
    tab: "Overview",
    focusKind: "activity",
    title: "New announcement",
    content: "A new update is available.",
  };
}
