import { InquiryWorkspaceSection } from "../sections/InquiryWorkspaceSection.jsx";
import { normalizePropertyId } from "@modules/details-workspace/exports/components.js";

export function InquiryWorkspaceArea({
  activeWorkspaceTab,
  mountedWorkspaceTabs,
  visibleWorkspaceTabs,
  setActiveWorkspaceTab,
  isInquiryInitialLoadInProgress,
  filteredRelatedDeals,
  relatedJobsForDisplay,
  hasMemoContext,
  isMemosLoading,
  memosError,
  memos,
  resolveMemoAuthor,
  handleOpenMemoPreview,
  plugin,
  linkedInquiryJobIdFromRecord,
  inquiryNumericId,
  isRelatedRecordsLoading,
  relatedRecordsError,
  relatedRecordsAccountId,
  selectedRelatedJobId,
  relatedJobIdByUid,
  handleToggleRelatedJobLink,
  isSavingLinkedJob,
  openRelatedRecord,
  contactLogsContactId,
  isContactLogsLoading,
  contactLogsError,
  contactLogs,
  workspaceLookupData,
  safeUid,
  uploadsPropertyId,
  handleOpenUploadModal,
  inquiryAppointmentPrefillContext,
  handleOpenCreateAppointmentModal,
  handleOpenEditAppointmentModal,
  activeRelatedProperty,
  selectedPropertyId,
  openContactDetailsModal,
  relatedRecordsAccountType,
  propertySearchQuery,
  propertySearchItems,
  handlePropertySearchValueChange,
  handlePropertySearchQueryChange,
  handleSelectPropertyFromSearch,
  handleOpenAddPropertyModal,
  linkedPropertiesSorted,
  isLinkedPropertiesLoading,
  linkedPropertiesError,
  setSelectedPropertyId,
  handleOpenEditPropertyModal,
  isApplyingSameAsContactProperty,
  isPropertySameAsContact,
  handleSameAsContactPropertyChange,
}) {
  return (
    <InquiryWorkspaceSection
      activeWorkspaceTab={activeWorkspaceTab}
      mountedWorkspaceTabs={mountedWorkspaceTabs}
      visibleWorkspaceTabs={visibleWorkspaceTabs}
      onChangeWorkspaceTab={setActiveWorkspaceTab}
      isInitialLoadInProgress={isInquiryInitialLoadInProgress}
      relatedData={{
        deals: filteredRelatedDeals,
        jobs: relatedJobsForDisplay,
        hasMemoContext,
        isMemosLoading,
        memosError,
        memos,
        resolveMemoAuthor,
        onOpenMemoPreview: handleOpenMemoPreview,
        plugin,
        linkedJobId: linkedInquiryJobIdFromRecord,
        inquiryId: inquiryNumericId,
        isLoading: isRelatedRecordsLoading,
        error: relatedRecordsError,
        hasAccount: Boolean(relatedRecordsAccountId),
        selectedRelatedJobId,
        jobIdByUid: relatedJobIdByUid,
        onToggleJobLink: handleToggleRelatedJobLink,
        isLinkingJob: isSavingLinkedJob,
        onNavigateToDeal: openRelatedRecord,
        onNavigateToJob: openRelatedRecord,
        hasContactLogsContext: Boolean(contactLogsContactId),
        isContactLogsLoading,
        contactLogsError,
        contactLogs,
      }}
      properties={{
        plugin,
        workspaceLookupData,
        linkedJobId: linkedInquiryJobIdFromRecord,
        inquiryId: inquiryNumericId,
        currentPropertyId: normalizePropertyId(activeRelatedProperty?.id || selectedPropertyId),
        onOpenContactDetailsModal: openContactDetailsModal,
        accountType: relatedRecordsAccountType,
        selectedAccountId: relatedRecordsAccountId,
        propertySearchValue: propertySearchQuery,
        propertySearchItems,
        onPropertySearchValueChange: handlePropertySearchValueChange,
        onPropertySearchQueryChange: handlePropertySearchQueryChange,
        onSelectPropertyFromSearch: handleSelectPropertyFromSearch,
        onAddProperty: handleOpenAddPropertyModal,
        activeRelatedProperty,
        linkedProperties: linkedPropertiesSorted,
        isLoading: isLinkedPropertiesLoading,
        loadError: linkedPropertiesError,
        selectedPropertyId: normalizePropertyId(activeRelatedProperty?.id || selectedPropertyId),
        onSelectProperty: setSelectedPropertyId,
        onEditRelatedProperty: handleOpenEditPropertyModal,
        sameAsContactLabel: isApplyingSameAsContactProperty ? "Applying..." : "Same as contact",
        isSameAsContactChecked: isPropertySameAsContact,
        isSameAsContactDisabled:
          isApplyingSameAsContactProperty || !inquiryNumericId || !plugin,
        onSameAsContactChange: handleSameAsContactPropertyChange,
      }}
      uploads={{
        plugin,
        linkedJobId: linkedInquiryJobIdFromRecord,
        inquiryId: inquiryNumericId,
        inquiryUid: safeUid,
        propertyId: uploadsPropertyId,
        onRequestAddUpload: handleOpenUploadModal,
      }}
      appointments={{
        plugin,
        linkedJobId: linkedInquiryJobIdFromRecord,
        workspaceLookupData,
        inquiryId: inquiryNumericId,
        inquiryUid: safeUid,
        prefillContext: inquiryAppointmentPrefillContext,
        onRequestCreate: handleOpenCreateAppointmentModal,
        onRequestEdit: handleOpenEditAppointmentModal,
      }}
    />
  );
}
