import { useJobAccountDerivedData } from "./useJobAccountDerivedData.js";
import { useJobStatusDerivedData } from "./useJobStatusDerivedData.js";

export function useJobScreenDerivedData({
  accountCompanyRecord,
  accountContactRecord,
  activeWorkspaceProperty,
  affiliations,
  allocatedServiceProviderId,
  companyLookupRecords,
  contactLookupRecords,
  effectiveJobId,
  isNewJob,
  jobActivities,
  jobMaterials,
  jobTakenByPrefillLabel,
  jobTakenBySearch,
  loadedAccountType,
  loadedAccountsContactId,
  loadedClientEntityId,
  loadedClientIndividualId,
  loadedJobStatus,
  loadedPropertyId,
  quotePaymentDetails,
  relatedInquiryId,
  relatedInquiryRecord,
  relatedInquiryUid,
  relatedRecords,
  routeJobStatus,
  safeUid,
  selectedAccountsContactId,
  selectedJobEmailContactId,
  selectedServiceProviderId,
  selectedWorkspacePropertyId,
  serviceProviderItems,
  serviceProviderSearch,
  workspacePropertyLookupRecords,
  workspacePropertySearchValue,
}) {
  const account = useJobAccountDerivedData({
    accountCompanyRecord,
    accountContactRecord,
    activeWorkspaceProperty,
    effectiveJobId,
    loadedAccountType,
    loadedClientEntityId,
    loadedClientIndividualId,
    loadedPropertyId,
    selectedWorkspacePropertyId,
  });

  const status = useJobStatusDerivedData({
    accountCompanyAddress: account.accountCompanyAddress,
    accountCompanyName: account.accountCompanyName,
    accountCompanyPrimaryName: account.accountCompanyPrimaryName,
    accountCompanyPrimaryPhone: account.accountCompanyPrimaryPhone,
    accountContactAddress: account.accountContactAddress,
    accountContactName: account.accountContactName,
    accountContactPhone: account.accountContactPhone,
    accountType: account.accountType,
    activePropertyAddress: account.activePropertyAddress,
    activeWorkspaceProperty,
    affiliations,
    allocatedServiceProviderId,
    companyLookupRecords,
    contactLookupRecords,
    effectiveJobId,
    isCompanyAccount: account.isCompanyAccount,
    isNewJob,
    isQuoteCompanyAccount: account.isQuoteCompanyAccount,
    jobActivities,
    jobMaterials,
    jobTakenByPrefillLabel,
    jobTakenBySearch,
    loadedAccountType,
    loadedClientEntityId,
    loadedClientIndividualId,
    loadedJobStatus,
    loadedPropertyId,
    quotePaymentDetails,
    relatedInquiryId,
    relatedInquiryRecord,
    relatedInquiryUid,
    relatedRecords,
    routeJobStatus,
    safeUid,
    selectedAccountsContactId,
    selectedJobEmailContactId,
    selectedServiceProviderId,
    selectedWorkspacePropertyId,
    serviceProviderItems,
    serviceProviderSearch,
    workspacePropertyLookupRecords,
    workspacePropertySearchValue,
    accountCompanyRecord,
    accountContactRecord,
  });

  return { ...account, ...status };
}
